<a href="https://colab.research.google.com/github/alzatiro-create/analisis-regresi-jambi/blob/main/Pandas_alza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

dataku = pd.read_csv("https://raw.githubusercontent.com/Alam-A99/DATAAKSI/main/dataset_fiskal_97_hipoFull.csv") # menambahkan raw dan usercontent, menghapus blob
# dataku.head()
# dataku.head(10)
# dataku.tail(15)
# dataku.shape
# dataku.info()
# dataku.columns
# dataku.describe
#--> statistik deskriptif
dataku[["DBH_PAJAK","Kota","Tahun"]]
#dataku[dataku["Tahun"] == 2024]
#dataku[dataku["Tahun"] >= 2020]
#dataku.sort_values("PAD") --> melihat data dari yang terkecil
#dataku.sort_values("PAD", ascending=False) --> melihat data dari yang terbesar
#dataku["PAD"].max() --> mencari PAD terbesar
#dataku.loc[dataku["PAD"].idxmax(),["Kota", "Tahun", "PAD"]] --> jika ingin mengetahui kota dll
#dataku["PAD"].min()
#dataku["PAD"].mean()
#dataku["PAD"].sum()
#dataku["Kota"].value_counts() --> menghitung jumlah data tiap kota

      DBH_PAJAK             Kota  Tahun
0         77.91  Kota Banda Aceh   2014
1         54.88  Kota Banda Aceh   2015
2         78.91  Kota Banda Aceh   2016
3         72.77  Kota Banda Aceh   2017
4         93.06  Kota Banda Aceh   2018
...         ...              ...    ...
1062     116.28      Kota Sorong   2020
1063     138.49      Kota Sorong   2021
1064     105.81      Kota Sorong   2022
1065      80.40      Kota Sorong   2023
1066      94.64      Kota Sorong   2024

[1067 rows x 3 columns]

In [ ]:
# Mencari pengangguran yang jumlahnya kurang dari 5
dataku.loc[dataku["PENGANGGURAN"] < 5,["Kota", "Tahun", "PENGANGGURAN"]]

                 Kota  Tahun  PENGANGGURAN
2     Kota Banda Aceh   2016          3.68
9     Kota Banda Aceh   2023          3.05
10    Kota Banda Aceh   2024          4.76
11        Kota Sabang   2014          4.69
12        Kota Sabang   2015          3.29
...               ...    ...           ...
1051     Kota Tarakan   2020          4.34
1055     Kota Tarakan   2024          4.73
1060      Kota Sorong   2018          3.09
1061      Kota Sorong   2019          4.78
1063      Kota Sorong   2021          3.27

[307 rows x 3 columns]

In [ ]:
# Melihat data PAD dari yang terkecil
dataku.sort_values("PAD")

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
783,Kota Kotamobagu,2016,11.55,10.02,10.74,22.33,17.62,16.66,20.79,24.06,...,254.33,251.29,116.26,280.56,52.67,15.22,7.76,0.43,83.56,6.35
782,Kota Kotamobagu,2015,14.14,11.61,6.73,27.46,14.62,14.05,21.82,25.74,...,106.52,99.39,297.28,107.03,294.63,16.81,9.89,0.30,77.48,5.89
786,Kota Kotamobagu,2019,13.13,10.64,10.93,32.37,25.78,24.42,17.71,27.25,...,162.51,159.06,78.41,175.48,264.96,17.68,9.38,0.46,63.20,5.70
914,Kota Tual,2015,12.96,8.93,10.32,24.69,15.56,16.35,19.12,27.30,...,135.24,83.42,71.53,59.82,263.13,17.91,6.13,0.48,71.70,4.69
915,Kota Tual,2016,13.46,5.94,9.03,24.84,16.41,18.73,15.04,27.71,...,279.32,283.85,165.95,213.73,114.48,16.62,9.63,0.32,63.89,5.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,Kota Tangerang,2022,292.00,162.60,139.18,480.05,188.25,207.17,255.61,596.15,...,253.12,229.32,181.06,197.20,222.28,5.54,9.89,0.39,68.98,2.46
251,Kota Pekanbaru,2023,277.09,215.37,92.45,317.57,288.44,213.47,236.88,604.75,...,219.38,55.64,156.72,94.58,188.51,6.00,7.54,0.31,69.39,6.39
570,Kota Malang,2023,230.13,146.90,116.35,477.08,277.64,271.48,224.39,611.50,...,275.60,59.95,205.74,65.17,293.26,5.58,9.10,0.40,69.96,2.87
967,Kota Cilegon,2024,222.11,193.53,146.37,465.72,253.62,236.20,322.04,616.90,...,128.73,51.84,171.32,275.23,162.52,9.82,3.72,0.31,62.36,7.57
1052,Kota Tarakan,2021,310.26,237.35,166.72,413.94,269.95,308.14,292.04,686.78,...,176.48,120.64,235.66,267.83,156.10,5.21,5.49,0.36,66.56,4.13

In [ ]:
# Mengetahui rata" PAD tiap kota
dataku.groupby("Kota")["PAD"].mean()

Kota
Kab. Kotabaru              127.548182
Kab. Kotawaringin Barat    263.739091
Kab. Kotawaringin Timur    387.152727
Kab. Lima Puluh Kota        70.131818
Kota Ambon                 103.959091
                              ...
Kota Ternate               135.465455
Kota Tidore Kepulauan      179.657273
Kota Tomohon               205.806364
Kota Tual                   39.487273
Kota Yogyakarta            228.340000
Name: PAD, Length: 97, dtype: float64

In [ ]:
# Menghitung jumalah data tiap kota
dataku["Kota"].value_counts()

Kota
Kota Banda Aceh        11
Kota Sabang            11
Kota Langsa            11
Kota Lhokseumawe       11
Kota Subulussalam      11
                       ..
Kota Gorontalo         11
Kota Batam             11
Kota Tanjung Pinang    11
Kota Tarakan           11
Kota Sorong            11
Name: count, Length: 97, dtype: int64